# Generated by Django 3.0.6 on 2020-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='태그명\x1c')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그s',
                'db_table': '태그',
            },
        ),
    ]
